volumes:
 dist:
 static_volume:

services:
 client:
  build:
   context: ./frontend
  container_name: client
  volumes:
   - dist:/site/dist

 server:
  build:
   context: ./backend
  container_name: server
  ports:
   - "8000:8000"
  command: gunicorn backend.wsgi:application --workers=5 --bind 0.0.0.0:8000
  volumes:
   - static_volume:/django_site/staticfiles
  extra_hosts:
   - "host.docker.internal:host-gateway"

 nginx:
  image: nginx:stable-alpine
  container_name: nginx
  volumes:
  # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
   - ./nginx/cert.pem:/etc/nginx/cert.pem
   - ./nginx/key.pem:/etc/nginx/key.pem
   - dist:/html
   - static_volume:/staticfiles
  ports:
   - "80:80"
   - "443:443"
  depends_on:
   - client
   - server